[package]
name = "cg-ir"
version = "0.1.0"
edition = "2021"
authors = ["Deepu Singh <dksingh1130@gmail.com>"]
license = "MIT"
description = "Intermediate representation (IR) for codegrep language parsers"
repository = "https://github.com/deepusingh2530/codegrep"
keywords = ["static-analysis", "security", "parser"]
categories = ["development-tools"]

[dependencies]
serde = { workspace = true }
anyhow = { workspace = true }
cg-parser = { path = "../cg-parser", version = "0.1.0" }
tree-sitter = { workspace = true }
