[package]
name = "cg-rules"
version = "0.2.1"
edition = "2021"
authors = ["Deepu Singh <dksingh1130@gmail.com>"]
license = "MIT"
description = "YAML rule schema, loading and indexing for codegrep"
repository = "https://github.com/deepusingh2530/codegrep"
keywords = ["static-analysis", "security", "parser"]
categories = ["development-tools"]

[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
anyhow = { workspace = true }
aho-corasick = { workspace = true }
